version: 2.1
 
jobs:
  build:
    machine:
      image: ubuntu-2004:current
      resource_class: large  
    steps:
      - run:
          name: Configure Minikube
          command: |
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
            sudo dpkg -i minikube_latest_amd64.deb
            minikube start --vm-driver=docker
            minikube addons enable registry
      - run:
          name: Check status
          command: |
            minikube status

workflows:
  version: 2
  minikube-example:
    jobs:
      - build