version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest .
      - run:
          name: Debug environment variables
          command: |
            echo "DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME"
            echo "DOCKER_HUB_PASSWORD: $DOCKER_HUB_PASSWORD"
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest

  test:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Pull Docker image from Docker Hub
          command: docker pull $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest
      - run:
          name: Run Docker container
          command: docker run -d -p 5000:5000 --name test-container $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest
      - run:
          name: Test the application
          command: |
            sleep 5  # Wait for the container to start
            curl -s http://localhost:5000 | grep "Hello, World!"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-push
      - test:
          requires:
            - build-and-push